Updates to Git, NodeJS, and VSCode versions
saltstack/salt-winrepo-ng pull request #1738
Opened 2020-11-04 17:12 UTC by jswan106

2020-11-11 17:40 UTC, didiatworkz commented
git version deprecated #1749 
node.js version deprecated #1756

2020-11-18 21:31 UTC, twangboy approved these changes

2020-11-18 21:31 UTC, twangboy commented
Looks like we have some conflicts here

2020-11-18 21:35 UTC, jswan106 commented
There we go, fixed the conflicts, should be good to go now.

2020-12-11 21:04 UTC, twangboy requested changes

2020-12-11 21:04 UTC, twangboy commented on vscode.sls
> +  {% for version, guid in (('1.50.1', 'd2e414d9e4239a252d1ab117bd7067f125afd80a'), ('1.49.3', '2af051012b66169dde0c4dfae3f5ef48f787ff69'), ('1.48.2', 'a0479759d6e9ea56afa657e454193f72aef85bd0'), ('1.
We need to keep the older versions around to allow for upgrade and uninstall of those older versions.

2020-12-16 21:57 UTC, twangboy approved these changes

2020-12-16 21:57 UTC, merged